### ISSUE TITLE
About flynet + CANN

### ISSUE THREAD

**Issue by SeaEastXu** [mchancan/flynet#2]
Hi! Excellent work you did.

I have some quesitons about flynet +CANN.
![fn](https://user-images.githubusercontent.com/14850488/86727802-57c1d100-c05e-11ea-8c99-183f634e7f95.png)

As shown above,the output of MLP is a probability score of each input image,and each neuron of CANN linearly connect to MLP.  
So how CANN process the output data of MLP? 
And what is the input unit V ? 
And the output of  CANN is max activity of n neurons,isn't it？

Looking forward to your kindly reply～

**Comment by mchancan** [comment]
Hi, thanks for your questions.

_So how CANN process the output data of MLP?_
- It process the MLP output just like a typical NN layer: at each time step, it takes the full FC scores.

_And what is the input unit V ?_
- As detailed in the paper: "activity shifts in our 1-d CANN model, representing movement through the environment, were implemented with a direct shift and copy action. Although this could be implemented with more biologically faithful details such as velocity (V) units and asymmetric connections". So, basically the unit V represent movement through the environment and it can be any signal that is capable of encoding this type of sensory information. In the paper we used a direct shift and copy action to simulate movement trought the environment as the image sequence is fed to the network. You may refer to the original RatSLAM implementation as an example on how to implement this type of input.

_And the output of CANN is max activity of n neurons,isn't it？_
- Yes.

**Comment by mchancan** [comment]
@SeaEastXu please check #3 where I've released a quick demo of a CANN implementation.

**Comment by SeaEastXu** [comment]
> @SeaEastXu please check #3 where I've released a quick demo of a CANN implementation.

thanks a lot
